name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-14, ubuntu-latest]
        python-version: ["3.8", "3.11"]
        include:
          - platform: windows-latest
            cmake_args: -DGGML_BMI2=OFF
          - platform: macos-14
            cmake_args: >-
              -DGGML_NATIVE=OFF 
              -DGGML_CPU_ARM_ARCH=armv8-a

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Install requirements
      run: python -m pip install -r requirements.txt

    - name: Build and install
      env:
        CMAKE_ARGS: ${{ matrix.cmake_args }}
        ARCHFLAGS: ${{ matrix.archflags }}
      run: pip install --verbose .[test]

#    - name: Test C-API
#      run: python -m unittest ./tests/test_c_api.py

